language: java

jdk:
 - openjdk11
 
 addons:
  sonarcloud:
    organization: "andreadepaolis95"
    token:
      secure: "43fddcc628656182d23f1ba92536c0fa9094c5b0"

script:
  - ant build
  - sonar-scanner
 
