language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "andreadepaolis95" # the key of the org you chose at step #3
    token:
     secure: "dzn0cIXhQHok7Yq2zU648m2ZdSpfsMR8gWPZ88gddyfV6e0nir0KZRFDQcj3/J3p+iChllQ8pY13LjDhJCKFtUE/gJgb1XdjxJ0ASFB0iyd/tnLPichnpdjV64nJh5NsZ9ISw1w6a2MnJdkS+bGJkxrndoWjkj1zg8vfEs+nPMEvC9Jb8/WnLKN7/n6SzbQGZzM//w0WCFfiI27x1iuAtthkl5nzg1IM9/6pu1EyUAna/PL3H/JveUReuDcdfIz++pCqakaS/OJR1wrft5RFerDII4ojh+98kSghfOqX6SHeQU1BdBjMiskJjSV+183RkBtqDS0QuKW869jrx6/9xIgCMIkrkEeNXeHNG8Rnb5SVlzOAKWqOTih7mGyLnqGDkDLJ4iYDmxYpp0hYeK9NeD/aqes297yCiBUYVowXd15l99sS2VJCyJxbBF/XVcLVsynbg/6/BU5LNu+oG+y2U5Dh8vIK8tCL/AbkR+8XC01dpE9X908zts16RgPll1QU+eEEzYV2cZ6V5TB9OmuwlzkRZLhSLuXdpf/qSjtriwYTIwn1WA0cg5i3PuWqSULI5X/tatLz0vpNI07lTRflPJPMqZ42K48jP9oBDiDYoQ4+RfE0/KlvoKtxEcE18ohRqBmfw153Ola/ddQ8nxo7GwxLCUbv0e/SJqjgCOZuPk8="

script:
  - ant build
  - sonar-scanner
 
