language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "andreadepaolis95" # the key of the org you chose at step #3
    token:
     secure: "ifLz2cdeCrpuI1VuoxU1mnuknHqflFOeTqkNjVirtZxKNNWYi6nn0IHo1Q4cc8y15zmd0+pIh912kYf5cvNpzbC5FgjvrX2CHhxVyBCOC8aWe1K+jW5Fu/ZFJS8LKdPvYdH6EbWBvDZWGQ6qpCmRhgW+0qRn9eRdxqjTvFk46M6BbKpKhCyvcYfARkuheyQEYtC+dHr5vHaAfXyoFZbE6cSqtP9SjFV9bUY2KfRLElYYut6R8B/mbl38tpNLsE32VQD6phMDMnNAHiSePsRYAC34X/vqQG3Xa+NvZicJykV61/PJZRs730kXbuhNx+/q13muUvvPEUYQOqxLkUO+cdXfAtGuxPXVSe7yEMX6FGYsdWpcfKRLtcS0NszzRa6mHrwy01Pq7wROA6+5VuspdbotY2EexFAzpPMiNSN4b+HD2ZdAGjmGFdoWjrp03AdpzQvaOqLYirF9cXx6hl3IiuK/g+3YGQ/+25WQoYj4s/XVlVZLly7Gkiv3IEUwgmMTCrp+pkE0Wihb25k9SGbmlFRY9NBJqcarCWSMxd/1o3BF8ypC4o+pOJ4l5mZemQ2ybD7gkrQ5kg2zvTt+NkprZB8LhhjDvAyocj2SdTaaZDHEtu9NR2NKnOUNAaN1nLd9i9QZppMx48SOuZ/dchI9uJLkscKG5W5BhjXta8GS9Y8="

script:
  - ant build
  - sonar-scanner
 
