language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "andreadepaolis95" # the key of the org you chose at step #3
    token:
     secure: "L3c+SuMe+MjTtqjaasEHgMPwG0q+3hpX+yFl0nFadU3T9OJT3MrwX7GgR4RdEnB6OOmVNpnv+Eh/m0ZDb+c7GHL4EabKBrorttLq0PGsVwvup90OqJdOtejZ8aFEPfxOO9fOPoZ69Zi+SRN5hAkhYMHqq2WxDu2RtkOOcdZzmAe7ZhQCbvWs+WUEOlWYexfFVUoOkC0hA4aPw0Pg4B3Ob37f/gvPA22H2R11ni+Gs7yS+V8CFfPk/Qjf2ifPLGxZrkQsB1Hakm3mwVwk7aLfBKyOxQNM1YNOF+lAqcRYFshftIE3gTmCFrkBbkUFHZOdscSHp3yC9Qt2ubpSSuii2j1a2xaF6gTVdrpwFoHkR2woeGcddlkO5fJki43CVR7qamLpcIBJe/qBZumbJ9ThCU51YX85/c4UDPfEhFZeDTBJ+Ry4hIx3CjebIZcLcoaHYhXWEItDUlOXbsA0K7ob5tEbaik50iXkDuy8WJhsqYAV3tpNRnu7cxy2LNSQLtZlT/CIXzwtYwmgKWPLYtdOtFy95KwseT4Htiyvg/JWz7a3m1ZTjBGGMI5lRi4/QMrdMZ6jSp8i3MdhDCnr/f4LqKqELWmIO9Dn86j2RLLVk7/F7nbOBbheFDWeLeVfqSpt1i+CJ/0LISVwnoZgmsV9tfsrT2lVwBz9arn3Cyx4AQY="
script:
  - ant build
  - sonar-scanner
 
