language: java

jdk:
 - openjdk11
 
addons:
  sonarcloud:
    organization: "andreadepaolis95" # the key of the org you chose at step #3
    token:
     secure: "QbYpF9w982XgpXmMHfgCkYQhLSkTP/qBV1bt+He0TJ1tl23aPHUFQBxikfN8M3IKMhb5nLQupiJ0pY0Z5Leuq9i3uxcKI9+DIRVKpcFCs8WlhXzK9oqFkHKYTUNnDpK9nQPDX4SuU4eJCdhhFq8yrgSlO+5voqKQdQRn4Lc51U/BMiPYBWLprC9onadpojlnfbOwXuO0VNijR+pulVunljiHtMao4fvjjn0fOAbA4Y3NVHXBaSB3RTJ7GE9asBLcU677kCZ//HOcolKnRHLWAhR5i5CpMV7sRE4RpFVvJTNpM0OU6wcRTSeXkiEMqUy5PFbDWJobtN4IPzVrJHHDwcwt+9c5IMM1wW+lFw+TyzJv3PNYdDizcER0B0k7RxLfzMdJieznXG0T/TN1hiLJRwJQikVpQv/hLeC50xvY0wsNGtUJlQrq7JYFHmIdVu7kOS05CQ7U4N73LROvrhvZ7HywDkFRCNlVDWC94ragvpecnIQErJmjd4i9cnf/rPBNfDfaMI1HNS1PiALRAt2WzEQ0j0xkJlPmRhkYlh3o+qFpCeo9+t0E2cQu63mevKAXgGUKlN9BNvd5+3QlaZEl0E1vu41K3SvzPRpEqIWV52weO0dQd4zmMeLGB1gwTnpFP5f/hIJMbVJ0of/l9B01gslAtO7x1uAFPM8m5txrRMQ="

script:
  - ant build
  - sonar-scanner
 
